// <auto-generated />
namespace Khnumdev.TwitBot.Data.DWH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixedLengthConversationId2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedLengthConversationId2));
        
        string IMigrationMetadata.Id
        {
            get { return "201606051838543_FixedLengthConversationId2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
